jwt:
  secret: '[a-zA-z0-9_]^+Guideline89797987forAlphabeticArraNumeralsandOtherSymbo$'








server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: letmein
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

